structure/core/views.py
import atexit
import csv
import os
from os import environ
from uuid import uuid4
import secrets
import random
import string
import requests
from requests.auth import HTTPBasicAuth
from apscheduler.schedulers.background import BackgroundScheduler
from flask import render_template, Blueprint, session, redirect, url_for, jsonify, current_app, request
from flask_login import login_required
from sqlalchemy import and_, or_, desc
from flask_mail import Mail, Message
from datetime import date,datetime
from structure import db,mail ,photos,app
from structure.core.forms import FilterForm,SipRequestForm , IssueForm,NumberSearchForm,ExtForm
from structure.about.forms import AboutForm
from structure.models import User , Organization , Issue ,IssueComment ,Discussion,DiscussionComment ,Poll, PollOption, PollVote ,LikeDislike , Favorite,Upload
from werkzeug.utils import secure_filename
from PIL import Image


core = Blueprint('core', __name__)



@core.context_processor
def utility_processor():
    def get_option_percentage(poll_id, option_id):
        total_votes = PollVote.query.filter_by(poll_id=poll_id).count()
        option_votes = PollVote.query.filter_by(poll_id=poll_id, option_id=option_id).count()
        return round((option_votes / total_votes) * 100, 2) if total_votes > 0 else 0

    return dict(get_option_percentage=get_option_percentage)
# def require_api_key(view_function):
#     def decorated_function(*args, **kwargs):
#         if request.headers.get('Authorization') == API_KEY:
#             return view_function(*args, **kwargs)
#         else:
#             return jsonify({'error': 'Invalid API key', 'status': False}), 401

#     return decorated_function

def generate_secure_password(length=12):
    alphabet = string.ascii_letters + string.digits + string.punctuation
    secure_password = ''.join(secrets.choice(alphabet) for _ in range(length))
    return secure_password


def get_total_likes(likeable_model, likeable_id):
    return LikeDislike.query.filter_by(likeable_type=likeable_model.__name__.lower(), likeable_id=likeable_id,value=1).count()

def get_total_dislikes(likeable_model, likeable_id):
    return LikeDislike.query.filter_by(likeable_type=likeable_model.__name__.lower(), likeable_id=likeable_id,value=0).count()


allowed_extensions = ['png', 'jpg', 'jpeg', 'gif','txt','pdf']
def check_file_extension(filename):
    return filename.rsplit('.', 1)[1].lower() in allowed_extensions


@core.route('/base')
def base():
    '''
    Example view of any other "core" page. Such as a info page, about page,
    contact page. Any page that doesn't really sync with one of the models.
    '''
    return render_template('base.html')

@core.route('/issues')
def issues():
    polls = Poll.query.all()
    organizations = Organization.query.all()
    issues = Issue.query.all()
    discussions = Discussion.query.all()
    return render_template('portal/issues.html', organizations = organizations,issues=issues,polls=polls,discussions=discussions)


@core.route('/myissues')
def myissues():
    polls = Poll.query.all()
    organizations = Organization.query.all()
    myissues = Issue.query.filter_by(user_id=session['id']).all()
    issues = Issue.query.all()
    discussions = Discussion.query.all()
    return render_template('portal/myissues.html', organizations = organizations,issues=issues,polls=polls,discussions=discussions)


@core.route('/discussions')
def discussions():
    discussions = Discussion.query.all()
    polls = Poll.query.all()
    issues = Issue.query.all()
    organizations = Organization.query.all()
    return render_template('portal/discussions.html', organizations = organizations,issues=issues,polls=polls,discussions=discussions)

@core.route('/mydiscussions')
def mydiscussions():
    polls = Poll.query.all()
    organizations = Organization.query.all()
    mydiscussions = Discussion.query.filter_by(user_id=session['id']).all()
    issues = Issue.query.all()
    discussions = Discussion.query.all()
    return render_template('portal/mydiscussions.html', organizations = organizations,mydiscussions=mydiscussions,polls=polls,discussions=discussions,issues=issues)


@core.route('/polls')
def polls():
    polls = Poll.query.all()
    issues = Issue.query.all()
    organizations = Organization.query.all()
    discussions = Discussion.query.all()
    return render_template('portal/polls.html', organizations = organizations,issues=issues,polls=polls,discussions=discussions)

@core.route('/mypolls')
def mypolls():
    polls = Poll.query.all()
    organizations = Organization.query.all()
    mypolls = Poll.query.filter_by(user_id=session['id']).all()
    issues = Issue.query.all()
    polls = Poll.query.all()
    discussions = Discussion.query.all()
    return render_template('portal/mypolls.html', organizations = organizations,mypolls=mypolls,polls=polls,discussions=discussions,issues=issues)




@core.route('/organizations')
def organizations():
    issues = Issue.query.all()
    organizations = Organization.query.all()
    polls = Poll.query.all()
    discussions = Discussion.query.all()
    return render_template('portal/organizations.html', organizations = organizations,issues=issues,polls=polls,discussions=discussions)

# @core.route('/')
# def home():
#     # user = User.query.filter_by(id=session['id']).first()
  
  
#     headers = {
#         'Content-Type': 'application/json'
#     }
#     # session.pop('msg', None)
#     # api_url = 'https://app.connexcs.com/api/cp/customer?status=inactive'
#     # # response = requests.get(api_url)
#     # response = requests.get(api_url, headers=headers,auth=HTTPBasicAuth(connex_username, connex_password))
#     # inactive = response.json() if response.status_code == 200 else []
#     # # print(response.content)
 
    


#     return render_template(
#         'web/index.html',
         
#     )




@core.route('/')
# @login_required
def dashboard():
    issues = Issue.query.all()
    discussions = Discussion.query.all()
    organizations = Organization.query.all()
    polls = Poll.query.all()
    return render_template(
        'portal/dashboard.html',issues=issues, discussions= discussions, organizations= organizations,polls=polls
         
    )


@core.route("/issues/new", methods=["GET", "POST"])
def new_issue():
    form = IssueForm()
    organizations  = Organization.query.all()
    # user = User.query.filter_by(id=session['id']).first()
    
    if request.method == "POST":

        print(form.description.data)
        issue = Issue(user_id=session['id'],description= form.description.data,title = form.title.data,
                       location = form.location.data,organization_id = form.organization.data ,date = datetime.now(),contact=form.contact.data
                          )
        db.session.add(issue)
        db.session.commit()
        uploaded_files = request.files.getlist('images')

        # Process and save each uploaded file to the database
        for img in uploaded_files:
            # if img:
            filename = secure_filename(img.filename)
            print(filename)
            # file.save(photos.config['UPLOADED_PHOTOS_DEST'] + '/' + filename)
            image = photos.save(img, name=secrets.token_hex(10) + ".")
            image= "static/uploads/issues/"+image

            # Save file details to the database and associate with the issue
            upload = Upload(filename=image, issue=issue, issue_id=issue.id)
            db.session.add(upload)
            db.session.commit()

  
    return render_template("portal/newissue.html",form=form,organizations=organizations)


@core.route('/issue/<int:issue_id>',methods=['GET', 'POST'])
def issue(issue_id):
    # form = NewsletterSubForm()
    issue =  Issue.query.filter(Issue.id == issue_id).first()
    issuecomments = IssueComment.query.filter_by(issue_id=issue_id, parent_comment_id=None).all()
    issue.views =issue.views + 1
    db.session.commit()
    title = issue.title
    related = Issue.query.all()
    discussions = Discussion.query.all()
    polls = Poll.query.all()
    issues = Issue.query.all()
    return render_template('portal/issue.html',issue=issue,title=title,issuecomments=issuecomments,related=related,discussions=discussions,polls=polls,issues=issues)


@core.route('/issue/<int:issue_id>/add_comment', methods=['POST'])
def add_comment(issue_id):
    issue = Issue.query.get(issue_id)
    user_id = session['id']  # Replace with the actual user ID
    content = request.form.get('content')
    parent_comment_id = request.form.get('parent_comment_id')
    if parent_comment_id:
        parent_comment = IssueComment.query.get(parent_comment_id)
        comment = IssueComment(issue=issue, user_id=user_id, content=content, parent_comment=parent_comment)
    else:
        comment = IssueComment(issue=issue, user_id=user_id, content=content)    
    db.session.add(comment)
    db.session.commit()

    return redirect(url_for('core.issue', issue_id=issue_id))


@core.route('/discussions')
def list_discussions():
    discussions = Discussion.query.all()
    return render_template('discussions.html', discussions=discussions)

@core.route('/discussion/<int:discussion_id>')
def view_discussion(discussion_id):
    total_likes = get_total_likes(Discussion, discussion_id)
    total_dislikes = get_total_dislikes(Discussion, discussion_id)
    print(total_likes)
    print("total_likes")
    discussion = Discussion.query.get(discussion_id)
    discussion.views = int(discussion.views) +1
    discussion.likes = total_likes
    discussion.dislikes = total_dislikes
    db.session.commit()
    discussions = Discussion.query.all()
    polls= Poll.query.all()
    comments = DiscussionComment.query.filter_by(discussion_id=discussion_id, parent_comment_id=None).all()
    
    return render_template('portal/discussion.html', discussion=discussion, comments=comments,discussions=discussions,polls=polls,total_likes=total_likes,total_dislikes=total_dislikes)

structure/templates/portal/dashboard.html
{% extends "portal/base.html" %}
{% block content %}
   

        <!-- main contents -->
        <main id="site__main" class="2xl:ml-[--w-side]  xl:ml-[--w-side-sm] p-2.5 h-[calc(100vh-var(--m-top))] mt-[--m-top]">

            <div class="2xl:max-w-[1220px] max-w-[1065px] mx-auto">

                <div class="page-heading">
                    
                    <h1 class="page-title"> DASHBOARD </h1>
    
                </div>
                <div class="sm:my-6 my-3 flex items-center justify-between lg:mt-10">
                    <div>
                        <h2 class="md:text-lg text-base font-semibold text-black"> New Issues </h2>
                        <p class="font-normal text-sm text-gray-500 leading-6"> Issues being reported </p>
                    </div>
                    <a href="{{url_for('core.issues')}}" class="text-blue-500 sm:block hidden text-sm"> See all </a>
                </div>
                <!-- event feautred -->
                <div class="relative" tabindex="-1" uk-slider="finite:true">
        
                    <div class="uk-slider-container pb-1">
                    
                        <ul class="uk-slider-items grid-small">
                           {%for issue in issues%}
                            <li class="lg:w-1/4 sm:w-1/3 w-1/2">
                                <div class="card">
                                    <a href="{{url_for('core.issue',issue_id=issue.id)}}">
                                        <div class="card-media h-32">
                                            <img src="/static/main/assets/images/events/img-3.jpg" alt="">
                                            <div class="card-overly"></div>
                                        </div>
                                    </a>
                                    <div class="card-body">
                                        <!-- <p class="text-xs font-medium text-blue-600 mb-1"> Next week </p>  -->
                                        <a href="{{url_for('core.issue',issue_id=issue.id)}}"><h4 class="card-title text-sm"> {{issue.title}} </h4> </a>
                                        <a href="{{url_for('core.issue',issue_id=issue.id)}}"> <p class="card-text text-black mt-2"> {{issue.location}} </p> </a> 
                                        <div class="card-list-info text-xs mt-1">
                                            <div> {{issue.views}} Views</div>
                                            <div class="md:block hidden">·</div>
                                            <div> {{issue.likes}} Likes</div>
                                        </div>
                                        <div class="flex gap-2">
                                            <a href="{{url_for('core.issue',issue_id=issue.id)}}" type="button" class="button bg-primary text-white flex-1">View</a>
                                        </div>
                                    </div>
                                </div>
                            </li> 
                            {%endfor%}
                            
                        </ul>
                
                    </div>
                
                    <!-- slide nav icons -->
                    <a class="nav-prev !top-20" href="#" uk-slider-item="previous"> <ion-icon name="chevron-back" class="text-2xl"></ion-icon> </a>
                    <a class="nav-next !top-20" href="#" uk-slider-item="next"> <ion-icon name="chevron-forward" class="text-2xl"></ion-icon></a>
                    
                </div>
    
    
               
    


                <!--Discussions-->







                <div class="sm:my-6 my-3 flex items-center justify-between lg:mt-10">
                    <div>
                        <h2 class="md:text-lg text-base font-semibold text-black"> Discussions </h2>
                        <p class="font-normal text-sm text-gray-500 leading-6"> Find Discussions You Might Be Interested In. </p>
                    </div>
                    <a href="{{url_for('core.discussions')}}" class="text-blue-500 sm:block hidden text-sm"> See all </a>
                </div>

                <div class="grid md:grid-cols-2 md:gap-2 gap-3">
                        {% for item in discussions%}
                    <div class="flex md:items-center space-x-4 p-4 rounded-md box">
                        <div class="sm:w-20 w-14 sm:h-20 h-14 flex-shrink-0 rounded-lg relative"> 
                            <img src="/static/main/assets/images/group/group-4.jpg" class="absolute w-full h-full inset-0 rounded-md object-cover shadow-sm" alt="">
                        </div> 
                        <div class="flex-1">
                            <a href="{{url_for('core.view_discussion',discussion_id=item.id)}}" class="md:text-lg text-base font-semibold capitalize text-black dark:text-white"> {{item.title}}  </a>
                            <div class="flex space-x-2 items-center text-sm font-normal">
                                <div> {{item.views}} Views</div>
                                <div>·</div>
                                <div> {{item.likes}} Likes</div>
                            </div>
                            <div class="flex items-center mt-2">
                                <img src="/static/main/assets/images/avatars/avatar-2.jpg" class="w-6 rounded-full border-2 border-gray-200 -mr-2" alt="">
                                <img src="/static/main/assets/images/avatars/avatar-4.jpg" class="w-6 rounded-full border-2 border-gray-200" alt="">
                                <div class="text-sm text-gray-500 ml-2"> {{item.comments|length}} Comments</div>
                            </div>

                        </div>
                        <a href="{{url_for('core.view_discussion',discussion_id=item.id)}}" type="button" class="button bg-primary-soft text-primary dark:text-white gap-1 max-md:hidden"> <ion-icon name="add-circle" class="text-xl -ml-1"></ion-icon>View</a>

                    </div>
                    {%endfor%}
                    </div>
                   
               
     
                
  <!-- listing  slider -->

  
  <div class="sm:my-6 my-3 flex items-center justify-between md:mt-10">
    <div>
        <h2 class="text-xl font-semibold"> Organizations</h2>
        <p class="font-normal text-sm text-gray-500 leading-6"> Popular organizations. </p>
    </div>
    <a href="{{url_for('core.organizations')}}" class="text-blue-500 sm:block hidden text-sm"> See all </a>
</div>
  <div class="mt-4" tabindex="-1" uk-slider="finite:true">
    
    <div class="uk-slider-container pb-1">
       
        <ul class="uk-slider-items grid-small">
            {%for organization in organizations%}
            <li class="md:w-1/5 sm:w-1/3 w-1/2">
                <a href="{{url_for('core.organization', organization_id=organization.id)}}">
                    <div class="relative rounded-lg overflow-hidden">
                        <img src="/static/main/assets/images/events/listing-1.jpg" alt="" class="h-36 w-full object-cover">
                        <div class="w-full bottom-0 absolute left-0 bg-gradient-to-t from-black/60 pt-10">
                            <div class="text-white p-5">
                                <div class="text-sm font-light"> {{organization.views}}  </div>
                                <div class="text-lg leading-3 mt-1.5"> {{organization.user.name}} </div> 
                            </div>
                        </div>
                    </div>
                </a>
            </li>
            {%endfor%} 
            
        </ul>

    </div>
   
    <!-- slide nav icons -->
    <a class="nav-prev" href="#" uk-slider-item="previous"> <ion-icon name="chevron-back" class="text-2xl"></ion-icon> </a>
    <a class="nav-next" href="#" uk-slider-item="next"> <ion-icon name="chevron-forward" class="text-2xl"></ion-icon></a>
    
</div>            


<div class="flex items-center justify-between text-black dark:text-white py-3 mt-6">
    <h3 class="text-xl font-semibold"> Polls </h3>
    <a href="{{url_for('core.polls')}}" class="text-sm text-blue-500">See all</a>
</div>          
<div class="grid lg:grid-cols-3 md:grid-cols-3 sm:grid-cols-2 gap-2.5 mt-4">
{%for poll in polls%}
    <div class="bg-white rounded-xl shadow p-5 px-6 border1 dark:bg-dark2">
       <h3 class="font-semibold text-base">  {{poll.question}} </h3>

       <ul class="relative space-y-2.5 text-sm mt-3" uk-accordion="active: 0">
        {% for option in poll.options %}

           <li class="rounded-md bg-secondery">
            <a href="{{ url_for('core.vote_poll', poll_id=poll.id, option_id=option.id) }}" class="flex items-center justify-between p-3 py-2 font-semibold group text-black dark:text-white uk-accordion-title">
                <a href="{{ url_for('core.vote_poll', poll_id=poll.id, option_id=option.id) }}">{{ option.option_text }}</a>
                <span class="text-sm text-gray-500">({{ get_option_percentage(poll.id, option.id) }}%)</span>
                <ion-icon name="chevron-down-outline" class="duration-200 -mr-0.5 text-base group-aria-expanded:rotate-180"></ion-icon>
            </a>
              
           </li>
    {%endfor%}
       
       
       </ul> 

   

   </div>
   {%endfor%}



</div>
                <div class="flex items-center justify-between text-black dark:text-white py-3 mt-6">
                    <h3 class="text-xl font-semibold"> Popular Issues </h3>
                    <a href="{{url_for('core.issues')}}" class="text-sm text-blue-500">See all</a>
                </div>              
     <!-- Groups You Manage  -->
 
                <!-- event grid -->
                <div class="grid lg:grid-cols-3 md:grid-cols-3 sm:grid-cols-2 gap-2.5 mt-4">
                    {% for issue in issues %}
                    <div class="card">
                        <a href="{{url_for('core.issue',issue_id=issue.id)}}">
                            <div class="card-media h-32">
                                <img src="/static/main/assets/images/events/img-1.jpg" alt="">
                                <div class="card-overly"></div>
                            </div>
                        </a>
                        <div class="card-body">
                            <a href="{{url_for('core.issue',issue_id=issue.id)}}"><h4 class="card-title text-sm"> {{issue.title}}</h4> </a>
                            <a href="#"> <p class="card-text text-black mt-2"> {{issue.location}} </p> </a> 
                            <div class="card-list-info text-xs mt-1">
                                <div> {{issue.views}} Views</div>
                                <div class="md:block hidden">·</div>
                                <div> {{issue.likes}} Likes</div>
                            </div>
                            <div class="flex gap-2">
                                <a href="{{url_for('core.issue',issue_id=issue.id)}}" type="button" class="button bg-primary text-white flex-1">View</a>
                            </div>
                        </div>
                    </div>
                    {%endfor%}
                    </div>
    
                </div>
                
            </div>
            
        </main>

    {% endblock %}

structure/templates/portal/discussions.html
{% extends "portal/base.html" %}
{% block content %}
 
        <!-- main contents -->
        <main id="site__main" class="2xl:ml-[--w-side]  xl:ml-[--w-side-sm] p-2.5 h-[calc(100vh-var(--m-top))] mt-[--m-top]">

            <div class="flex max-lg:flex-col 2xl:gap-12 gap-10 2xl:max-w-[1220px] max-w-[1065px] mx-auto" id="js-oversized">

                <div class="flex-1">
     
                    <div class="max-w-[680px] w-full mx-auto">

                        <div class="page-heading">
                            <h1 class="page-title"> Discussions </h1>
                        </div>
        
                        <!-- groups -->
                        <div class="box p-5">
        
                         
                            
                        </div>
        
                        <!-- tab 2 -->
                        <nav class="mt-8 dark:border-slate-700 mb-6">
                        
                            <ul class="flex gap-2 text-xs text-center text-gray-600 capitalize font-semibold dark:text-white/80" uk-switcher="connect: #tabs2 ; animation: uk-animation-slide-right-medium, uk-animation-slide-left-medium"> 
                            
                                <li> 
                                    <a href="#" class="inline-flex items-center gap-2 py-2.5 px-4 rounded-full aria-expanded:text-white aria-expanded:bg-black"> 
                                        New 
                                    </a> 
                                </li>  
                                <li> 
                                    <a href="#" class="inline-flex items-center gap-2 py-2.5 px-4 rounded-full aria-expanded:text-white aria-expanded:bg-black"> 
                                        Popular 
                                    </a>
                                </li>   
                        
                            </ul> 
        
                        </nav>
                        
                        <div id="tabs2" class="uk-switcher">
        
                            <!-- layouy 1 -->
                            <div>
                <!-- articale list layout -->
                <div class="box p-5 mt-4">
                    {% for discussion in discussions%}

                    <div class="card-list">
                        <a href="{{url_for('core.view_discussion',discussion_id=discussion.id)}}" class="lg:order-1">
                            <div class="card-list-media h-100">
                                <img src="/static/main/assets/images/blog/img-2.jpg" alt="">
                            </div>
                        </a>
                        <div class="card-list-body">
                            <a href="{{url_for('core.view_discussion',discussion_id=discussion.id)}}"> <h3 class="card-list-title"> {{discussion.title}} </h3> </a>
                            <p class="card-list-text"> {{discussion.content}}</p>
                            <a href="#"> <div class="card-list-link"> username</div> </a>
                            <div class="card-list-info">
                                <div class="flex items-center gap-2"> 
                                    <ion-icon name="heart-outline" class="text-lg"></ion-icon>
                                    {{discussion.views}} views
                                </div>
                                <div class="md:block hidden">·</div>
                                <div class="flex items-center gap-2"> 
                                    <ion-icon name="chatbubble-ellipses-outline" class="text-lg"></ion-icon>
                                    {{discussion.likes}}
                                </div>
                            </div>
                        </div>
                    </div>
                  
                    {% for comment in discussion.comments %}

                    <div class="flex items-start gap-3 ">

                    <a href="timeline.html"> <img src="/static/main/assets/images/avatars/avatar-3.jpg" alt="" class="w-6 h-6 mt-1 rounded-full"> </a>
                    <div class="flex-1">
                        <a href="timeline.html" class="text-black font-medium inline-block dark:text-white"> {{comment.user.username}} </a>
                        <p class="mt-0.5">  {{comment.content}} </p>
                      
                    </div>
                </div>
                {%endfor%}
                    <button type="button" class="flex items-center gap-1.5 text-gray-500 hover:text-blue-500 mt-2">
                        <ion-icon name="chevron-down-outline" class="ml-auto duration-200 group-aria-expanded:rotate-180"></ion-icon>
                        More Comments
                    </button>


                <!-- add comment -->
                <div class="sm:px-4 sm:py-3 p-2.5 border-t border-gray-100 flex items-center gap-1 dark:border-slate-700/40">
                    
                    
                    <div class="flex-1 relative overflow-hidden h-10">
                        <form action="{{ url_for('core.add_discussion_comment', discussion_id=discussion.id) }}" method="post">

                        <textarea name="content" placeholder="Add Comment...." rows="1" class="w-full resize-none !bg-transparent px-4 py-2 focus:!border-transparent focus:!ring-transparent"></textarea>

                  
                        

                    </div>
                    

                    <button type="submit" class="text-sm rounded-full py-1.5 px-3.5 bg-secondery"> Comment</button>
                </form>

                </div> 
                    <hr class="card-list-divider">
                    {%endfor%}
                </div>
        
                <!-- show more -->
                <div class="flex justify-center my-6">
                    <button type="button" class="bg-white py-2 px-5 rounded-full shadow-md font-semibold text-sm dark:bg-dark2">Load more...</button>
                </div>

            </div>

        </div>

    </div>


</div> 

<!-- sidebar -->
<div class="2xl:w-[380px] lg:w-[330px] w-full">

    <div class="lg:space-y-6 space-y-4 lg:pb-8 max-lg:grid sm:grid-cols-2 max-lg:gap-6" uk-sticky="media: 1024; end: #js-oversized; offset: 80">

        <div class="box p-5 px-6">

            <div class="flex items-baseline justify-between text-black dark:text-white">
                <h3 class="font-bold text-base"> Popular Issues</h3>
                <a href="#" class="text-sm text-blue-500">See all Issues</a>
            </div>
        
            <div class="side-list">
                {% for issue in issues[:5]%}
                <div class="side-list-item">
                    <a href="{{url_for('core.issue', issue_id=issue.id)}}">
                        <img src="/static/main/assets/images/avatars/avatar-2.jpg" alt="" class="side-list-image rounded-md">
                    </a>
                    <div class="flex-1">
                        <a href="{{url_for('core.issue', issue_id=issue.id)}}"><h4 class="side-list-title"> {{issue.title}}</h4></a>
                        <div class="side-list-info"> {{issue.views}} </div>
                    </div>
                    <a href="{{url_for('core.issue', issue_id=issue.id)}}"  class="button bg-secondery">View</a>
                </div>
                {%endfor%}
                 
                 
            </div>
            <button class="bg-secondery w-full text-black py-1.5 font-medium px-3.5 rounded-md text-sm mt-3 dark:text-white">See all</button>

        </div>

         <!-- Groups You Manage  -->
         <div class="bg-white rounded-xl shadow p-5 px-6 border1 dark:bg-dark2">
                        
            <div class="flex items-baseline justify-between text-black dark:text-white">
                <h3 class="font-bold text-base"> Popular Polls </h3>
                <a href="#" class="text-sm text-blue-500">See all</a>
            </div>

            <div class="side-list">
                {% for poll in polls[:5]%}
                <div class="side-list-item">
                    <a href="timeline-group.html">
                        <img src="assets/images/avatars/avatar-2.jpg" alt="" class="side-list-image rounded-md">
                    </a>
                    <div class="flex-1">
                        <a href="timeline-group.html"><h4 class="side-list-title">  {{poll.question}}</h4></a>
                        <div class="side-list-info"> </div>
                    </div>
                    <button class="button bg-primary-soft text-primary dark:text-white">Like</button>
                </div>
                {%endfor%}
                 
                 
            </div>

            <a href="{{url_for('core.polls')}}"  class="bg-secondery w-full text-black py-1.5 font-medium px-3.5 rounded-md text-sm mt-3 dark:text-white">See all</a>

        </div>

        <!-- Groups You Manage  -->
        <div class="bg-white rounded-xl shadow p-5 px-6 border1 dark:bg-dark2">
                        
            <div class="flex items-baseline justify-between text-black dark:text-white">
                <h3 class="font-bold text-base"> Suggested Discussions </h3>
                <a href="#" class="text-sm text-blue-500">See all</a>
            </div>

            <div class="side-list">
                {%for discussion in discussions[:5]%}
            <div class="side-list-item">
                <a href="timeline-group.html">
                    <img src="/static/main/assets/images/avatars/avatar-2.jpg" alt="" class="side-list-image rounded-md">
                </a>
                <div class="flex-1">
                    <a  href="{{url_for('core.view_discussion', discussion_id=discussion.id)}}" ><h4 class="side-list-title">  {{discussion.title}}</h4></a>
                    <div class="side-list-info"> {{discussion.views}} views </div>
                </div>
                <button class="button bg-primary text-white">{{discussion.likes}} likes</button>
            </div>
            {%endfor%}
        
           
             
        </div>
        

            <a href="{{url_for('core.discussions')}}"  class="bg-secondery w-full text-black py-1.5 font-medium px-3.5 rounded-md text-sm mt-3 dark:text-white">See all</a>

        </div>

    </div> 

</div>

</div>


</main>

</div>




<div class="w-3.5 h-3.5 absolute -bottom-2 right-5 bg-white rotate-45 dark:bg-dark3"></div>
</div>
</div>

    {% endblock %}